import { Outfit, Bitter, Poppins } from "next/font/google";
import "./globals.css";
import "@/styles/about.css"
import "@/styles/banner.css"
import Footer from "@/components/Home/Footer/Footer";

const bitter = Bitter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"]
});

const outfit = Outfit({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "600", "700"]
});

export const metadata = {
  title: "Next Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bitter.variable} ${outfit.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
