name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Triggers when you push to the main branch

permissions:
  contents: write  # Allows GitHub Actions to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Set your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build and export
        run: |
          npm run build
          npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
